# Generated by Django 2.1.5 on 2023-03-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
